### PR TITLE
Bot testing

### PR DESCRIPTION
**Pull request by gauntface**

### CODE REVIEW

**Comment by gauntface** [comment]
This is an example comment

**Comment by travis-bot-gauntface** [comment]
This is an example comment

**Comment by travis-bot-gauntface** [comment]
This is an example comment

**Comment by travis-bot-gauntface** [comment]
# Info from travis-bot

## 🎉 'travis-bot.plugins.Size'

### Changed File Sizes

| | File Path | File Size | Units |
| --- | --- | --- | --- |


<details>
<summary>Full File List</summary>

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/Assertions.js | 103 | B |
|  | packages/workbox-core/build/umd-development.js | 2.863 | KB |
|  | packages/workbox-core/build/umd-production.js | 2.709 | KB |
|  | packages/workbox-core/example-change.js | 22 | B |
|  | packages/workbox-core/module.js | 1.398 | KB |
|  | packages/workbox-core/RequestWrapper.js | 973 | B |
|  | packages/workbox-core/src/Assertions.js | 97 | B |
|  | packages/workbox-core/src/LogHelper.js | 218 | B |
|  | packages/workbox-core/umd.js | 57 | B |
|  | packages/workbox-loader/umd.js | 1.184 | KB |
|  | packages/workbox-precaching/build/umd-development.js | 1.574 | KB |
|  | packages/workbox-precaching/build/umd-production.js | 1.396 | KB |
|  | packages/workbox-precaching/module.js | 96 | B |
|  | packages/workbox-precaching/PrecacheController.js | 848 | B |
|  | packages/workbox-precaching/src/error-messages.js | 227 | B |
|  | packages/workbox-precaching/umd.js | 148 | B |
|  | packages/workbox-routing/build/umd-development.js | 1.483 | KB |
|  | packages/workbox-routing/build/umd-production.js | 1.483 | KB |
|  | packages/workbox-routing/ExpressRoute.js | 160 | B |
|  | packages/workbox-routing/module.js | 60 | B |
|  | packages/workbox-routing/NavigationRoute.js | 166 | B |
|  | packages/workbox-routing/RegExpRoute.js | 158 | B |
|  | packages/workbox-routing/Route.js | 150 | B |
|  | packages/workbox-routing/Router.js | 275 | B |
|  | packages/workbox-routing/umd.js | 329 | B |
|  | packages/workbox-strategies/build/umd-development.js | 1.035 | KB |
|  | packages/workbox-strategies/build/umd-production.js | 1.035 | KB |
|  | packages/workbox-strategies/CacheFirst.js | 455 | B |
|  | packages/workbox-strategies/module.js | 0 | B |
|  | packages/workbox-strategies/umd.js | 64 | B |

</details>

**Comment by travis-bot-gauntface** [comment]
# Info from travis-bot

## 🎉 'travis-bot.plugins.Size'

### Changed File Sizes

| | File Path | File Size | Units |
| --- | --- | --- | --- |


<details>
<summary>Full File List</summary>

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/Assertions.js | 103 | B |
|  | packages/workbox-core/build/umd-development.js | 2.863 | KB |
|  | packages/workbox-core/build/umd-production.js | 2.709 | KB |
|  | packages/workbox-core/example-change.js | 33 | B |
|  | packages/workbox-core/module.js | 1.398 | KB |
|  | packages/workbox-core/RequestWrapper.js | 973 | B |
|  | packages/workbox-core/src/Assertions.js | 97 | B |
|  | packages/workbox-core/src/LogHelper.js | 218 | B |
|  | packages/workbox-core/umd.js | 57 | B |
|  | packages/workbox-loader/umd.js | 1.184 | KB |
|  | packages/workbox-precaching/build/umd-development.js | 1.574 | KB |
|  | packages/workbox-precaching/build/umd-production.js | 1.396 | KB |
|  | packages/workbox-precaching/module.js | 96 | B |
|  | packages/workbox-precaching/PrecacheController.js | 848 | B |
|  | packages/workbox-precaching/src/error-messages.js | 227 | B |
|  | packages/workbox-precaching/umd.js | 148 | B |
|  | packages/workbox-routing/build/umd-development.js | 1.483 | KB |
|  | packages/workbox-routing/build/umd-production.js | 1.483 | KB |
|  | packages/workbox-routing/ExpressRoute.js | 160 | B |
|  | packages/workbox-routing/module.js | 60 | B |
|  | packages/workbox-routing/NavigationRoute.js | 166 | B |
|  | packages/workbox-routing/RegExpRoute.js | 158 | B |
|  | packages/workbox-routing/Route.js | 150 | B |
|  | packages/workbox-routing/Router.js | 275 | B |
|  | packages/workbox-routing/umd.js | 329 | B |
|  | packages/workbox-strategies/build/umd-development.js | 1.035 | KB |
|  | packages/workbox-strategies/build/umd-production.js | 1.035 | KB |
|  | packages/workbox-strategies/CacheFirst.js | 455 | B |
|  | packages/workbox-strategies/module.js | 0 | B |
|  | packages/workbox-strategies/umd.js | 64 | B |

</details>

**Comment by travis-bot-gauntface** [comment]
# Results from Plugins

## Travis-Bot Size Plugin

### Changed File Sizes

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/example-change.js | 33 | B |

<details>
<summary>Full List of File Sizes</summary>

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/Assertions.js | 103 | B |
|  | packages/workbox-core/build/umd-development.js | 2.863 | KB |
|  | packages/workbox-core/build/umd-production.js | 2.709 | KB |
|  | packages/workbox-core/example-change.js | 33 | B |
|  | packages/workbox-core/module.js | 1.398 | KB |
|  | packages/workbox-core/RequestWrapper.js | 973 | B |
|  | packages/workbox-core/src/Assertions.js | 97 | B |
|  | packages/workbox-core/src/LogHelper.js | 218 | B |
|  | packages/workbox-core/umd.js | 57 | B |
|  | packages/workbox-loader/umd.js | 1.184 | KB |
|  | packages/workbox-precaching/build/umd-development.js | 1.574 | KB |
|  | packages/workbox-precaching/build/umd-production.js | 1.396 | KB |
|  | packages/workbox-precaching/module.js | 96 | B |
|  | packages/workbox-precaching/PrecacheController.js | 848 | B |
|  | packages/workbox-precaching/src/error-messages.js | 227 | B |
|  | packages/workbox-precaching/umd.js | 148 | B |
|  | packages/workbox-routing/build/umd-development.js | 1.483 | KB |
|  | packages/workbox-routing/build/umd-production.js | 1.483 | KB |
|  | packages/workbox-routing/ExpressRoute.js | 160 | B |
|  | packages/workbox-routing/module.js | 60 | B |
|  | packages/workbox-routing/NavigationRoute.js | 166 | B |
|  | packages/workbox-routing/RegExpRoute.js | 158 | B |
|  | packages/workbox-routing/Route.js | 150 | B |
|  | packages/workbox-routing/Router.js | 275 | B |
|  | packages/workbox-routing/umd.js | 329 | B |
|  | packages/workbox-strategies/build/umd-development.js | 1.035 | KB |
|  | packages/workbox-strategies/build/umd-production.js | 1.035 | KB |
|  | packages/workbox-strategies/CacheFirst.js | 455 | B |
|  | packages/workbox-strategies/module.js | 0 | B |
|  | packages/workbox-strategies/umd.js | 64 | B |

</details>

**Comment by addyosmani** [comment]
Thanks for making a start on this, dude! 

Wdyt about a similar layout to what Lyft use?

image

**Comment by travis-bot-gauntface** [comment]
# Results from Plugins

## Travis-Bot Size Plugin

### Changed File Sizes

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/example-change.js | 103 | B |

<details>
<summary>Full List of File Sizes</summary>

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/Assertions.js | 103 | B |
|  | packages/workbox-core/build/umd-development.js | 2.863 | KB |
|  | packages/workbox-core/build/umd-production.js | 2.709 | KB |
|  | packages/workbox-core/example-change.js | 103 | B |
|  | packages/workbox-core/module.js | 1.398 | KB |
|  | packages/workbox-core/RequestWrapper.js | 973 | B |
|  | packages/workbox-core/src/Assertions.js | 97 | B |
|  | packages/workbox-core/src/LogHelper.js | 218 | B |
|  | packages/workbox-core/umd.js | 57 | B |
|  | packages/workbox-loader/umd.js | 1.184 | KB |
|  | packages/workbox-precaching/build/umd-development.js | 1.574 | KB |
|  | packages/workbox-precaching/build/umd-production.js | 1.396 | KB |
|  | packages/workbox-precaching/module.js | 96 | B |
|  | packages/workbox-precaching/PrecacheController.js | 848 | B |
|  | packages/workbox-precaching/src/error-messages.js | 227 | B |
|  | packages/workbox-precaching/umd.js | 148 | B |
|  | packages/workbox-routing/build/umd-development.js | 1.483 | KB |
|  | packages/workbox-routing/build/umd-production.js | 1.483 | KB |
|  | packages/workbox-routing/ExpressRoute.js | 160 | B |
|  | packages/workbox-routing/module.js | 60 | B |
|  | packages/workbox-routing/NavigationRoute.js | 166 | B |
|  | packages/workbox-routing/RegExpRoute.js | 158 | B |
|  | packages/workbox-routing/Route.js | 150 | B |
|  | packages/workbox-routing/Router.js | 275 | B |
|  | packages/workbox-routing/umd.js | 329 | B |
|  | packages/workbox-strategies/build/umd-development.js | 1.035 | KB |
|  | packages/workbox-strategies/build/umd-production.js | 1.035 | KB |
|  | packages/workbox-strategies/CacheFirst.js | 455 | B |
|  | packages/workbox-strategies/module.js | 0 | B |
|  | packages/workbox-strategies/umd.js | 64 | B |

</details>

**Comment by travis-bot-gauntface** [comment]
# Results from Plugins

## Travis-Bot Size Plugin

### Changed File Sizes

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/example-change.js | 103 | B |

<details>
<summary>Full List of File Sizes</summary>

| | File Path | File Size | Units |
| --- | --- | --- | --- |
|  | packages/workbox-core/Assertions.js | 103 | B |
|  | packages/workbox-core/build/umd-development.js | 2.863 | KB |
|  | packages/workbox-core/build/umd-production.js | 2.709 | KB |
|  | packages/workbox-core/example-change.js | 103 | B |
|  | packages/workbox-core/module.js | 1.398 | KB |
|  | packages/workbox-core/RequestWrapper.js | 973 | B |
|  | packages/workbox-core/src/Assertions.js | 97 | B |
|  | packages/workbox-core/src/LogHelper.js | 218 | B |
|  | packages/workbox-core/umd.js | 57 | B |
|  | packages/workbox-loader/umd.js | 1.184 | KB |
|  | packages/workbox-precaching/build/umd-development.js | 1.574 | KB |
|  | packages/workbox-precaching/build/umd-production.js | 1.396 | KB |
|  | packages/workbox-precaching/module.js | 96 | B |
|  | packages/workbox-precaching/PrecacheController.js | 848 | B |
|  | packages/workbox-precaching/src/error-messages.js | 227 | B |
|  | packages/workbox-precaching/umd.js | 148 | B |
|  | packages/workbox-routing/build/umd-development.js | 1.483 | KB |
|  | packages/workbox-routing/build/umd-production.js | 1.483 | KB |
|  | packages/workbox-routing/ExpressRoute.js | 160 | B |
|  | packages/workbox-routing/module.js | 60 | B |
|  | packages/workbox-routing/NavigationRoute.js | 166 | B |
|  | packages/workbox-routing/RegExpRoute.js | 158 | B |
|  | packages/workbox-routing/Route.js | 150 | B |
|  | packages/workbox-routing/Router.js | 275 | B |
|  | packages/workbox-routing/umd.js | 329 | B |
|  | packages/workbox-strategies/build/umd-development.js | 1.035 | KB |
|  | packages/workbox-strategies/build/umd-production.js | 1.035 | KB |
|  | packages/workbox-strategies/CacheFirst.js | 455 | B |
|  | packages/workbox-strategies/module.js | 0 | B |
|  | packages/workbox-strategies/umd.js | 64 | B |

</details>

**Comment by travis-bot-gauntface** [comment]
# Results from Plugins

## Travis-Bot Size Plugin

## Changed File Sizes

No file sizes have changed.

## New Files

| File | Size |
| --- | --- |
| packages/workbox-core/example-change.js | 138 B |

<details>
<summary>All File</summary>

| File | Before | After | Change |  |
| --- | --- | --- | --- | --- |
| packages/workbox-core/Assertions.js                  | 103 B    | 103 B    | 0.00% | |
| packages/workbox-core/build/umd-development.js       | 2.863 KB | 2.863 KB | 0.00% | |
| packages/workbox-core/build/umd-production.js        | 2.709 KB | 2.709 KB | 0.00% | |
| packages/workbox-core/example-change.js              | null B   | 138 B    |       | |
| packages/workbox-core/module.js                      | 1.398 KB | 1.398 KB | 0.00% | |
| packages/workbox-core/RequestWrapper.js              | 973 B    | 973 B    | 0.00% | |
| packages/workbox-core/src/Assertions.js              | 97 B     | 97 B     | 0.00% | |
| packages/workbox-core/src/LogHelper.js               | 218 B    | 218 B    | 0.00% | |
| packages/workbox-core/umd.js                         | 57 B     | 57 B     | 0.00% | |
| packages/workbox-loader/umd.js                       | 1.184 KB | 1.184 KB | 0.00% | |
| packages/workbox-precaching/build/umd-development.js | 1.574 KB | 1.574 KB | 0.00% | |
| packages/workbox-precaching/build/umd-production.js  | 1.396 KB | 1.396 KB | 0.00% | |
| packages/workbox-precaching/module.js                | 96 B     | 96 B     | 0.00% | |
| packages/workbox-precaching/PrecacheController.js    | 848 B    | 848 B    | 0.00% | |
| packages/workbox-precaching/src/error-messages.js    | 227 B    | 227 B    | 0.00% | |
| packages/workbox-precaching/umd.js                   | 148 B    | 148 B    | 0.00% | |
| packages/workbox-routing/build/umd-development.js    | 1.483 KB | 1.483 KB | 0.00% | |
| packages/workbox-routing/build/umd-production.js     | 1.483 KB | 1.483 KB | 0.00% | |
| packages/workbox-routing/ExpressRoute.js             | 160 B    | 160 B    | 0.00% | |
| packages/workbox-routing/module.js                   | 60 B     | 60 B     | 0.00% | |
| packages/workbox-routing/NavigationRoute.js          | 166 B    | 166 B    | 0.00% | |
| packages/workbox-routing/RegExpRoute.js              | 158 B    | 158 B    | 0.00% | |
| packages/workbox-routing/Route.js                    | 150 B    | 150 B    | 0.00% | |
| packages/workbox-routing/Router.js                   | 275 B    | 275 B    | 0.00% | |
| packages/workbox-routing/umd.js                      | 329 B    | 329 B    | 0.00% | |
| packages/workbox-strategies/build/umd-development.js | 1.035 KB | 1.035 KB | 0.00% | |
| packages/workbox-strategies/build/umd-production.js  | 1.035 KB | 1.035 KB | 0.00% | |
| packages/workbox-strategies/CacheFirst.js            | 455 B    | 455 B    | 0.00% | |
| packages/workbox-strategies/module.js                | 0 B      | 0 B      |       | |
| packages/workbox-strategies/umd.js                   | 64 B     | 64 B     | 0.00% | |

</details>

**Comment by travis-bot-gauntface** [comment]
# Results from Plugins

## Travis-Bot Size Plugin

## Changed File Sizes

No file sizes have changed.

## New Files

| File | Size |
| --- | --- |
| packages/workbox-core/example-change.js | 138 B |

<details>
<summary>All File</summary>

| File | Before | After | Change |  |
| --- | --- | --- | --- | --- |
| packages/workbox-core/Assertions.js                  | 103 B    | 103 B    | 0.00% | |
| packages/workbox-core/build/umd-development.js       | 2.863 KB | 2.863 KB | 0.00% | |
| packages/workbox-core/build/umd-production.js        | 2.709 KB | 2.709 KB | 0.00% | |
| packages/workbox-core/example-change.js              |          | 138 B    |       | |
| packages/workbox-core/module.js                      | 1.398 KB | 1.398 KB | 0.00% | |
| packages/workbox-core/RequestWrapper.js              | 973 B    | 973 B    | 0.00% | |
| packages/workbox-core/src/Assertions.js              | 97 B     | 97 B     | 0.00% | |
| packages/workbox-core/src/LogHelper.js               | 218 B    | 218 B    | 0.00% | |
| packages/workbox-core/umd.js                         | 57 B     | 57 B     | 0.00% | |
| packages/workbox-loader/umd.js                       | 1.184 KB | 1.184 KB | 0.00% | |
| packages/workbox-precaching/build/umd-development.js | 1.574 KB | 1.574 KB | 0.00% | |
| packages/workbox-precaching/build/umd-production.js  | 1.396 KB | 1.396 KB | 0.00% | |
| packages/workbox-precaching/module.js                | 96 B     | 96 B     | 0.00% | |
| packages/workbox-precaching/PrecacheController.js    | 848 B    | 848 B    | 0.00% | |
| packages/workbox-precaching/src/error-messages.js    | 227 B    | 227 B    | 0.00% | |
| packages/workbox-precaching/umd.js                   | 148 B    | 148 B    | 0.00% | |
| packages/workbox-routing/build/umd-development.js    | 1.483 KB | 1.483 KB | 0.00% | |
| packages/workbox-routing/build/umd-production.js     | 1.483 KB | 1.483 KB | 0.00% | |
| packages/workbox-routing/ExpressRoute.js             | 160 B    | 160 B    | 0.00% | |
| packages/workbox-routing/module.js                   | 60 B     | 60 B     | 0.00% | |
| packages/workbox-routing/NavigationRoute.js          | 166 B    | 166 B    | 0.00% | |
| packages/workbox-routing/RegExpRoute.js              | 158 B    | 158 B    | 0.00% | |
| packages/workbox-routing/Route.js                    | 150 B    | 150 B    | 0.00% | |
| packages/workbox-routing/Router.js                   | 275 B    | 275 B    | 0.00% | |
| packages/workbox-routing/umd.js                      | 329 B    | 329 B    | 0.00% | |
| packages/workbox-strategies/build/umd-development.js | 1.035 KB | 1.035 KB | 0.00% | |
| packages/workbox-strategies/build/umd-production.js  | 1.035 KB | 1.035 KB | 0.00% | |
| packages/workbox-strategies/CacheFirst.js            | 455 B    | 455 B    | 0.00% | |
| packages/workbox-strategies/module.js                | 0 B      | 0 B      |       | |
| packages/workbox-strategies/umd.js                   | 64 B     | 64 B     | 0.00% | |

</details>

**Comment by travis-bot-gauntface** [comment]
# Results from Plugins

## Travis-Bot Size Plugin

## Changed File Sizes

No file sizes have changed.

## New Files

| File | Size |
| --- | --- |
| packages/workbox-core/example-change.js | 138 B |

<details>
<summary>All Files</summary>

| File | Before | After | Change |  |
| --- | --- | --- | --- | --- |
| packages/workbox-core/Assertions.js                  | 103 B    | 103 B    | 0.00% | |
| packages/workbox-core/build/umd-development.js       | 2.863 KB | 2.863 KB | 0.00% | |
| packages/workbox-core/build/umd-production.js        | 2.709 KB | 2.709 KB | 0.00% | |
| packages/workbox-core/example-change.js              |          | 138 B    |       | |
| packages/workbox-core/module.js                      | 1.398 KB | 1.398 KB | 0.00% | |
| packages/workbox-core/RequestWrapper.js              | 973 B    | 973 B    | 0.00% | |
| packages/workbox-core/src/Assertions.js              | 97 B     | 97 B     | 0.00% | |
| packages/workbox-core/src/LogHelper.js               | 218 B    | 218 B    | 0.00% | |
| packages/workbox-core/umd.js                         | 57 B     | 57 B     | 0.00% | |
| packages/workbox-loader/umd.js                       | 1.184 KB | 1.184 KB | 0.00% | |
| packages/workbox-precaching/build/umd-development.js | 1.574 KB | 1.574 KB | 0.00% | |
| packages/workbox-precaching/build/umd-production.js  | 1.396 KB | 1.396 KB | 0.00% | |
| packages/workbox-precaching/module.js                | 96 B     | 96 B     | 0.00% | |
| packages/workbox-precaching/PrecacheController.js    | 848 B    | 848 B    | 0.00% | |
| packages/workbox-precaching/src/error-messages.js    | 227 B    | 227 B    | 0.00% | |
| packages/workbox-precaching/umd.js                   | 148 B    | 148 B    | 0.00% | |
| packages/workbox-routing/build/umd-development.js    | 1.483 KB | 1.483 KB | 0.00% | |
| packages/workbox-routing/build/umd-production.js     | 1.483 KB | 1.483 KB | 0.00% | |
| packages/workbox-routing/ExpressRoute.js             | 160 B    | 160 B    | 0.00% | |
| packages/workbox-routing/module.js                   | 60 B     | 60 B     | 0.00% | |
| packages/workbox-routing/NavigationRoute.js          | 166 B    | 166 B    | 0.00% | |
| packages/workbox-routing/RegExpRoute.js              | 158 B    | 158 B    | 0.00% | |
| packages/workbox-routing/Route.js                    | 150 B    | 150 B    | 0.00% | |
| packages/workbox-routing/Router.js                   | 275 B    | 275 B    | 0.00% | |
| packages/workbox-routing/umd.js                      | 329 B    | 329 B    | 0.00% | |
| packages/workbox-strategies/build/umd-development.js | 1.035 KB | 1.035 KB | 0.00% | |
| packages/workbox-strategies/build/umd-production.js  | 1.035 KB | 1.035 KB | 0.00% | |
| packages/workbox-strategies/CacheFirst.js            | 455 B    | 455 B    | 0.00% | |
| packages/workbox-strategies/module.js                | 0 B      | 0 B      |       | |
| packages/workbox-strategies/umd.js                   | 64 B     | 64 B     | 0.00% | |

</details>

**Pull request closed without merging**
